require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/season_viewings", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SeasonViewing. As you add validations to SeasonViewing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SeasonViewing.create! valid_attributes
      get season_viewings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      season_viewing = SeasonViewing.create! valid_attributes
      get season_viewing_url(season_viewing)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_season_viewing_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      season_viewing = SeasonViewing.create! valid_attributes
      get edit_season_viewing_url(season_viewing)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SeasonViewing" do
        expect {
          post season_viewings_url, params: { season_viewing: valid_attributes }
        }.to change(SeasonViewing, :count).by(1)
      end

      it "redirects to the created season_viewing" do
        post season_viewings_url, params: { season_viewing: valid_attributes }
        expect(response).to redirect_to(season_viewing_url(SeasonViewing.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SeasonViewing" do
        expect {
          post season_viewings_url, params: { season_viewing: invalid_attributes }
        }.to change(SeasonViewing, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post season_viewings_url, params: { season_viewing: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested season_viewing" do
        season_viewing = SeasonViewing.create! valid_attributes
        patch season_viewing_url(season_viewing), params: { season_viewing: new_attributes }
        season_viewing.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the season_viewing" do
        season_viewing = SeasonViewing.create! valid_attributes
        patch season_viewing_url(season_viewing), params: { season_viewing: new_attributes }
        season_viewing.reload
        expect(response).to redirect_to(season_viewing_url(season_viewing))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        season_viewing = SeasonViewing.create! valid_attributes
        patch season_viewing_url(season_viewing), params: { season_viewing: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested season_viewing" do
      season_viewing = SeasonViewing.create! valid_attributes
      expect {
        delete season_viewing_url(season_viewing)
      }.to change(SeasonViewing, :count).by(-1)
    end

    it "redirects to the season_viewings list" do
      season_viewing = SeasonViewing.create! valid_attributes
      delete season_viewing_url(season_viewing)
      expect(response).to redirect_to(season_viewings_url)
    end
  end
end
